# Generated by Django 5.0.3 on 2024-04-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Track', '0003_track_auditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artistImg', models.ImageField(upload_to='artistsImg/')),
                ('likes', models.IntegerField(default=0)),
                ('tracks', models.ManyToManyField(to='Track.track')),
            ],
        ),
    ]
