# Generated by Django 5.0.3 on 2024-04-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
