# Generated by Django 5.0.3 on 2024-05-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0002_alter_artist_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='big_img',
            field=models.ImageField(null=True, upload_to='artistsBigImg/'),
        ),
    ]
