# Generated by Django 5.0.3 on 2024-06-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0003_artist_big_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='likes',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
