# Generated by Django 5.0.3 on 2024-03-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=155)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('liked_track_list', models.TextField()),
                ('playlists_list', models.TextField()),
                ('self_token', models.CharField(max_length=40)),
                ('isHashed', models.BooleanField(default=False)),
            ],
        ),
    ]
