# Generated by Django 5.0.3 on 2024-03-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isHashed',
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_track_list',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='playlists_list',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='self_token',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
