# Generated by Django 5.0.3 on 2024-04-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0002_alter_track_albumimg_alter_track_id_and_more'),
        ('User', '0002_remove_user_ishashed_alter_user_liked_track_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='playlists_list',
        ),
        migrations.AddField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='self_description',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked_track_list',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_track_list',
            field=models.ManyToManyField(to='Track.track'),
        ),
    ]
