# Generated by Django 5.0.3 on 2024-05-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0003_artist_big_img'),
        ('User', '0004_alter_user_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_artists',
            field=models.ManyToManyField(to='Artists.artist'),
        ),
    ]
