# Generated by Django 5.0.3 on 2024-06-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_liked_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='self_description',
        ),
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='userImg/'),
        ),
    ]
