# Generated by Django 5.0.3 on 2024-03-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('title', models.CharField(max_length=155, verbose_name='Название')),
                ('artists', models.CharField(max_length=200, verbose_name='Артисты')),
                ('albumImg', models.CharField(max_length=300, verbose_name='Путь к обложке')),
                ('music', models.CharField(max_length=300, verbose_name='Путь к треку')),
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
