# Generated by Django 5.0.3 on 2024-03-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='albumImg',
            field=models.ImageField(upload_to='albumsImg/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='music',
            field=models.FileField(upload_to='music/'),
        ),
    ]
