# Generated by Django 5.0.3 on 2024-04-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0002_alter_track_albumimg_alter_track_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='auditions',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
