# Generated by Django 5.0.3 on 2024-06-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0003_track_auditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='auditions',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
